# Generated by Django 5.1.4 on 2024-12-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Contact',
        ),
    ]
