# Generated by Django 5.1.4 on 2025-01-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0003_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='emai',
            new_name='email',
        ),
    ]
