# Generated by Django 5.1.4 on 2025-01-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0004_rename_emai_testimonial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile',
            field=models.ImageField(default=1, upload_to='testimonial/'),
        ),
    ]
